version: '3.9'
services:
  server:
    restart: on-failure
    build: ./
    ports:
      - '5000:5000'
    networks:
      - vocally-network
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - '27017:27017'
    networks:
      - vocally-network
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - server
    networks:
      - vocally-network

networks:
  vocally-network:
    external: true
